# Generated by Django 2.2.5 on 2021-06-27 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grandhospital_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='first_namr',
            new_name='first_name',
        ),
    ]
