# Generated by Django 2.2.5 on 2021-06-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grandhospital_App', '0002_auto_20210627_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='address_2',
        ),
        migrations.AddField(
            model_name='appointment',
            name='avatar',
            field=models.ImageField(null=True, upload_to='appointment_candidate_pics'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='problem',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
