# Generated by Django 2.2.5 on 2021-06-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grandhospital_App', '0003_auto_20210628_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Choose your Gender', max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.IntegerField(blank=True, max_length=20),
        ),
    ]
