# Generated by Django 2.2.5 on 2021-06-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grandhospital_App', '0007_auto_20210628_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB-'), ('AB-', 'AB-')], default='A+', max_length=4),
        ),
    ]
