# Generated by Django 2.2.5 on 2021-06-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grandhospital_App', '0008_appointment_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('blood', 'Blood Group'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB-'), ('AB-', 'AB-')], default='blood', max_length=15),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='gender',
            field=models.CharField(blank=True, choices=[('gender', 'Gender'), ('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='gender', max_length=10),
        ),
    ]
