# Generated by Django 2.2.5 on 2021-06-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grandhospital_App', '0009_auto_20210628_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='dob',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
