# Generated by Django 2.2.5 on 2021-06-28 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grandhospital_App', '0012_auto_20210628_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 16, 9, 50, 393119)),
        ),
    ]
