# Generated by Django 2.2.5 on 2021-06-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grandhospital_App', '0014_auto_20210628_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='first_name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
