# Generated by Django 2.2.5 on 2021-06-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grandhospital_App', '0015_auto_20210628_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='address_1',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='city',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='first_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='gender',
            field=models.CharField(choices=[('gender', 'Gender'), ('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='gender', max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='last_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='problem',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user_mail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='zipcode',
            field=models.IntegerField(max_length=10),
        ),
    ]
